version: '3.4'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:     
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    stdin_open: true
    tty: true
    command: rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/pet_tracking_app
      - ./db:/app/db
    env_file: .env

  db:
    image: postgres:12.1
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust 

  redis:
    image: redis:7.0 
    ports:
      - "6379:6379"

volumes:
  db_data: {}